apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit262-group2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit262-group2
  template:
    metadata:
      labels:
        app: cit262-group2
    spec:
      containers:
      - name: cit262-group2
        image: gcr.io/potent-galaxy-274115/cit262-group2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cit262-group2-service
spec:
  selector:
    app: cit262-group2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cit262-group2-loadbalancer
spec:
  selector:
    app: cit262-group2
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
   
